#Numpy Arrays - Tips and Tricks
Here are some tricks that would come in handy while using Numpy Arrays

Let's say we need an array filled with -1 and +1 in a random manner. We can create this array in different ways.

In [4]:
from numpy.random import random
import math
# To get an array filled with -1 and 1 at random
array = random(10)
print(array)
abs(math.floor(-0.5))
array[array<0.5] = -1
array[array>=0.5] = +1
print(array)

[ 0.17494951  0.72570896  0.26675058  0.6290513   0.70916473  0.25818768
  0.79973822  0.02196009  0.03698919  0.01612405]
[-1.  1. -1.  1.  1. -1.  1. -1. -1. -1.]


This method replaces values above 0.5 with +1 and the rest with -1. This isn't the best method. Let's see a better way to create such an array

In [6]:
import numpy as np
# Better way
print(np.random.randint(-1,1,10))   # integers between -1 and 1. Useful if zero is also required.
print(np.random.choice([-1,1],10))  # fills with -1 and 1 only

[ 0  0 -1  0 -1 -1  0  0  0  0]
[ 1 -1 -1  1  1  1 -1 -1  1  1]


###Incrementally increasing or decreasing values

Let's say we are modelling a game and the score increases and decreases at each stage by 1. We can create an array one element at a time with a for loop, each time randomly adding +1 or -1 to the previous element. But this is not very efficient. Here's a more efficient way to achieve this.

In [7]:
array = np.random.choice([-1,1],10)  # use randint if there are turns where the score does not change
print(array)
print(array.cumsum())

[ 1  1 -1 -1  1 -1 -1  1  1 -1]
[ 1  2  1  0  1  0 -1  0  1  0]


To summarize, we created an array of +1 and -1 to represent the random increments or decrements. We could have filled it with other integers too, depending on the charactersitics of the changes.
Next, we use cumsum function to actually add each increment value to the previous element of the array. Pretty neat, eh? :)

###Conditionally modify elements of an array

To manipulate the elements based on conditions, you might reach for a for loop. But try to avoid for loops as much as you can, if performance is a concern. 

Instead, use conditional selection with truth arrays. See the example below

In [9]:
array = np.random.randint(-10,10,10)
array

array([  1,   7, -10,   8,  -6, -10,  -9,   8,   4,   8])

Now, if you want to apply a condition that positive integeres should be replaced with +1 and negative integeres with -1, you can do that in the following manner without using loops.

In [10]:
array[array<0] = -1
array[array>0] = +1
array

array([ 1,  1, -1,  1, -1, -1, -1,  1,  1,  1])

To be continued...